@ApiUser_HostAddress =apiuser20240919141944.azurewebsites.net
//@ApiUser_HostAddress = https://apispiderwatcheruser.azurewebsites.net

GET {{ApiUser_HostAddress}}/weatherforecast/
Accept: application/json

###
  