//@Api_HostAddress =http://localhost:8084
@ApiHistoryPlayback_HostAddress = https://apispiderwatcherhistoryplayback.azurewebsites.net

GET {{ApiHistoryPlayback_HostAddress}}/weatherforecast/
Accept: application/json

###
